[tool.poetry]
name = "ndn-python-svs"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
ndn-storage = "^0.2.3"

[tool.poetry.group.dev.dependencies]
python-ndn = "^0.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
